version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: airvzxf/python_ecommerce_web:dev
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 80M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
