version: '3'

services:

  mysql:
    image: python_ecommerce_database:dev
    container_name: python_ecommerce_database_dev
    restart: always
    ports:
      - 3306:3306/tcp
    networks:
      - webnet

  phpmyadmin:
    image: python_ecommerce_phpmyadmin:dev
    container_name: python_ecommerce_phpmyadmin_dev
    restart: always
    environment:
     - PMA_HOST=python_ecommerce_database_dev
    ports:
      - 8080:80/tcp
    networks:
      - webnet
    depends_on:
     - mysql

  web_service:
    image: python_ecommerce_web_service:dev
    container_name: python_ecommerce_web_service_dev
    restart: always
    command: ["./run.sh", "0.0.0.0", "8000", "mysql", "3306"]
    ports:
      - 8000:8000/tcp
    networks:
      - webnet
    depends_on:
     - mysql

  web:
    image: python_ecommerce_web:dev
    container_name: python_ecommerce_web_dev
    restart: always
    ports:
      - 80:3000/tcp
    networks:
      - webnet
    depends_on:
     - web_service

networks:
  webnet:
