version: '3.2'

services:

  db:
    image: python_ecommerce_database:dev
    container_name: python_ecommerce_database_dev
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306/tcp

  phpmyadmin:
    depends_on:
      - db
    image: python_ecommerce_phpmyadmin:dev
    container_name: python_ecommerce_phpmyadmin_dev
    restart: always
    ports:
      - 8080:80/tcp

  web:
    image: python_ecommerce_web:dev
    container_name: python_ecommerce_web_dev
    restart: always
    ports:
      - 80:80/tcp
    environment:
      NAME: "cool Developer"
