version: '3.7'

services:

  mysql:
    image: python_ecommerce_database:dev
    container_name: python_ecommerce_database_dev
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306/tcp
    networks:
      - webnet

  phpmyadmin:
    image: python_ecommerce_phpmyadmin:dev
    container_name: python_ecommerce_phpmyadmin_dev
    restart: always
    ports:
      - 8080:80/tcp
    networks:
      - webnet
    depends_on:
     - mysql

  web_service:
    image: python_ecommerce_web_service:dev
    container_name: python_ecommerce_web_service_dev
    restart: always
    command: ["./run.sh", "0.0.0.0", "8001", "mysql", "3306"]
    ports:
      - 8001:8001/tcp
    networks:
      - webnet
    depends_on:
     - mysql

networks:
  webnet:
